import "./globals.css"
import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import { Providers } from "@/redux/provider"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"

const montserrat = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Anemia Chartify",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <ToastContainer
            hideProgressBar
            theme="colored"
            newestOnTop
            draggable={false}
            toastStyle={{ color: "#333333" }}
          />
          {children}
        </Providers>
      </body>
    </html>
  )
}
